export const UPDATE_TENANCY_INFO = "UPDATE_TENANCY_INFO";
export const UPDATE_PROPERTY_INFO = "UPDATE_PROPERTY_INFO";
export const UPDATE_LANDLORD_INFO = "UPDATE_LANDLORD_INFO";
export const UPDATE_TENANT_INFO = "UPDATE_TENANT_INFO";
export const DELETE_TENANTTWO_INFO = "DELETE_TENANTTWO_INFO";
export const DELETE_TENANTTHREE_INFO = "DELETE_TENANTTHREE_INFO";
export const DELETE_TENANTFOUR_INFO = "DELETE_TENANTFOUR_INFO";
